on: 
  push:
    branches:
      - main

jobs:
  hellow_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          who-to-greet: 'Tom Granqvist'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"